export const GOALS=[10000,25000,50000,100000,500000,1000000];
export const CATALOG=[['iPhone 8',64,900,0],['iPhone XR',64,1350,0],['iPhone 11',128,1850,0],['iPhone 12',128,2450,0],['iPhone 13',128,3500,10000],['iPhone 14',128,4200,10000],['iPhone 15',128,5100,10000],['iPhone 14 Pro',256,5200,25000],['iPhone 15 Pro Max',256,7200,25000],['Samsung Galaxy S24 Ultra',256,6800,25000],['iPhone 16 Pro Max',256,8900,50000]];
const ISSUES=[['Tela paralela',.19],['Face ID com defeito',.24],['Câmera com defeito',.20],['Aparelho bloqueado',.78],['Peça substituída',.1]];
const NAMES=['Carlos','Mariana','Lucas','Marcos','Beatriz','Rafael','Camila','Pedro','Fernanda','André'];
const round=n=>Math.round(n/10)*10;
export const money=n=>new Intl.NumberFormat('pt-BR',{style:'currency',currency:'BRL',maximumFractionDigits:0}).format(n);
export const active=s=>s.inventory.filter(p=>p.status!=='vendido');
export const value=(s,p)=>Math.max(50,round(s.prices[p.model]*(1-(p.battery<80?.13:0)-(p.appearance<7?.07:0)-(p.box?0:.03)-p.issues.reduce((a,x)=>a+x[1],0))));
export const worth=s=>s.cash+active(s).reduce((a,p)=>a+value(s,p),0);
export const profit=s=>s.inventory.filter(p=>p.status==='vendido').reduce((a,p)=>a+p.soldPrice-p.cost,0)-s.expenses;
export const potential=(s,p,price)=>price-p.cost-p.inspectionCost;
function log(s,text,type='info'){s.feed.unshift({day:s.day,text,type,id:++s.seq});s.feed=s.feed.slice(0,180);}
function device(s,index,rng=Math.random){const [model,storage]=CATALOG[index];const issues=rng()<.32?[ISSUES[Math.floor(rng()*ISSUES.length)]]:[];return {id:++s.seq,model,storage,battery:Math.floor(74+rng()*25),appearance:Math.floor(6+rng()*5),box:rng()>.25,issues,inspected:false,revealed:false,inspectionCost:0,price:round(s.prices[model]*(.61+rng()*.51)),created:s.day,color:['violet','blue','mint','graphite'][Math.floor(rng()*4)]};}
export function initial(rng=Math.random){const s={version:1,seq:0,day:1,cash:5000,reputation:50,expenses:0,inventory:[],market:[],offers:[],feed:[],prices:Object.fromEntries(CATALOG.map(c=>[c[0],c[2]])),history:[{day:1,worth:5000}],highWater:5000,unlocked:0,goals:[],marketMood:1};const first=device(s,4,rng);Object.assign(first,{price:2500,battery:87,appearance:8,box:true,issues:[],color:'violet',featured:true});s.market=[first,...[2,3,1].map(i=>device(s,i,rng))];log(s,'Você encontrou um iPhone 13 128GB por R$ 2.500. Seu primeiro negócio começa aqui.','opportunity');return s;}
function getMarket(s,id){const p=s.market.find(p=>p.id===id);if(!p)throw Error('Esta oportunidade não está mais disponível.');return p;}
function getItem(s,id){const p=active(s).find(p=>p.id===id);if(!p)throw Error('Aparelho indisponível.');return p;}
function amount(n){if(!Number.isFinite(n)||n<50||n>1000000)throw Error('Informe um valor entre R$ 50 e R$ 1.000.000.');return Math.round(n);}
export function inspect(s,id){const p=getMarket(s,id);if(p.inspected)throw Error('Este aparelho já foi inspecionado.');if(s.cash<80)throw Error('Saldo insuficiente para a inspeção.');s.cash-=80;s.expenses+=80;p.inspected=true;p.inspectionCost=80;log(s,`Inspeção do ${p.model}: ${p.issues.length?p.issues.map(i=>i[0]).join(', '):'nenhum defeito oculto encontrado'}. Custo: R$ 80.`,'inspection');checkpoint(s);}
export function buy(s,id){const p=getMarket(s,id);if(s.cash<p.price)throw Error('Saldo insuficiente para comprar este aparelho.');s.cash-=p.price;s.market=s.market.filter(x=>x.id!==id);s.inventory.push({...p,cost:p.price,bought:s.day,status:'comprado',asking:null,views:0});log(s,`Você comprou o ${p.model} por ${money(p.price)}.`,'purchase');checkpoint(s);}
export function prepare(s,id){const p=getItem(s,id);if(p.status==='comprado')p.status='preparando anúncio';}
export function list(s,id,asking){const p=getItem(s,id);asking=amount(asking);if(p.issues.length&&!p.revealed){p.revealed=true;log(s,`Na preparação do ${p.model}, você identificou: ${p.issues.map(i=>i[0]).join(', ')}. O valor de revenda foi ajustado.`,'warning');}s.offers=s.offers.filter(o=>o.itemId!==id);p.asking=asking;p.listed=s.day;p.status='anunciado';log(s,`Você anunciou o ${p.model} por ${money(asking)}. Todos os defeitos identificados estão descritos no anúncio.`,'listing');}
function sell(s,o,price){const p=getItem(s,o.itemId);p.status='vendido';p.soldPrice=price;p.soldDay=s.day;s.cash+=price;s.offers=s.offers.filter(x=>x.itemId!==p.id);s.reputation=Math.min(100,s.reputation+3);log(s,`${o.buyer} comprou seu ${p.model}. Compra: ${money(p.cost)} · Venda: ${money(price)} · Lucro líquido: ${money(price-p.cost-p.inspectionCost)}.`,'sale');checkpoint(s);return 'accepted';}
export function negotiate(s,id,action,counter,rng=Math.random){const o=s.offers.find(o=>o.id===id);if(!o)throw Error('Esta proposta expirou.');const p=getItem(s,o.itemId);if(action==='accept')return sell(s,o,o.amount);if(action==='reject'){s.offers=s.offers.filter(x=>x.id!==id);p.status=s.offers.some(x=>x.itemId===p.id)?'negociando':'anunciado';log(s,`Você recusou a proposta de ${o.buyer} pelo ${p.model}.`);return 'rejected';}counter=amount(counter);log(s,`Você fez uma contraproposta de ${money(counter)} para ${o.buyer}.`);if(counter<=o.budget)return sell(s,o,counter);if(counter<=o.budget*1.16&&o.rounds<2&&rng()<.75){o.amount=round(Math.min(o.budget,o.amount+(o.budget-o.amount)*.65));o.rounds++;o.expires=s.day+2;log(s,`${o.buyer} negociou novamente: ${money(o.amount)} pelo ${p.model}.`,'offer');return 'counter';}s.offers=s.offers.filter(x=>x.id!==id);p.status=s.offers.some(x=>x.itemId===p.id)?'negociando':'anunciado';log(s,`${o.buyer} recusou a contraproposta e encerrou a negociação.`,'warning');return 'rejected';}
export function checkpoint(s){const w=worth(s);s.highWater=Math.max(w,s.highWater);for(const g of GOALS)if(w>=g&&!s.goals.includes(g)){s.goals.push(g);log(s,`Meta alcançada: ${money(g)} de patrimônio!`,'milestone');}const tier=s.highWater>=50000?50000:s.highWater>=25000?25000:s.highWater>=10000?10000:0;if(tier>s.unlocked){s.unlocked=tier;log(s,'Novos modelos desbloqueados no marketplace!','milestone');}const last=s.history.at(-1);if(last.day===s.day)last.worth=w;else s.history.push({day:s.day,worth:w});s.history=s.history.slice(-60);}
export function nextDay(s,rng=Math.random){s.day++;s.marketMood=1;const expired=s.offers.filter(o=>o.expires<s.day);s.offers=s.offers.filter(o=>o.expires>=s.day);for(const o of expired){s.reputation=Math.max(0,s.reputation-1);log(s,`A proposta de ${o.buyer} expirou sem resposta. Reputação: −1 ponto.`,'warning');}if(s.day%30>=26){s.marketMood=.93;log(s,'Final de mês: compradores estão oferecendo valores menores.','market');}if(rng()<.27){const event=Math.floor(rng()*3);if(event===0){for(const c of CATALOG)if(c[0].startsWith('iPhone'))s.prices[c[0]]=Math.max(100,round(s.prices[c[0]]*.94));log(s,'Apple anunciou um novo iPhone. Modelos antigos perderam 6% de valor.','market');}else if(event===1){s.prices['iPhone 13']=round(s.prices['iPhone 13']*1.04);log(s,'Alta procura por iPhone 13: preço médio subiu 4%.','market');}else{s.marketMood=.92;log(s,'Promoções de Black Friday: as ofertas de compradores caem 8% hoje.','market');}}
for(const p of active(s)){if(!p.revealed&&p.issues.length&&s.day>p.bought){p.revealed=true;log(s,`Defeito descoberto no ${p.model}: ${p.issues.map(i=>i[0]).join(', ')}. Valor estimado reduzido para ${money(value(s,p))}.`,'warning');}if(!p.asking)continue;p.status=s.offers.some(o=>o.itemId===p.id)?'negociando':'anunciado';const days=s.day-p.listed;const views=Math.floor((12+rng()*65)*(.55+s.reputation/100));p.views+=views;log(s,`Seu anúncio do ${p.model} recebeu ${views} visualizações.`);if(days===6)log(s,`O ${p.model} está anunciado há 6 dias. O tempo parado começa a reduzir as ofertas.`,'warning');const v=value(s,p);const probability=Math.max(.07,Math.min(.92,(.36+s.reputation*.005)*(v/p.asking)));if(!s.offers.some(o=>o.itemId===p.id)&&rng()<probability){const age=Math.max(.75,1-Math.max(0,days-5)*.012);const budget=round(v*(.88+s.reputation*.0015+rng()*.09)*age*s.marketMood);const offer=Math.max(50,round(Math.min(p.asking,budget*(.87+rng()*.08))));s.offers.push({id:++s.seq,itemId:p.id,buyer:NAMES[Math.floor(rng()*NAMES.length)],amount:offer,budget:Math.max(offer,budget),rounds:0,created:s.day,expires:s.day+2});p.status='negociando';log(s,`${s.offers.at(-1).buyer} ofereceu ${money(offer)} pelo seu ${p.model}.`,'offer');}}
s.market=s.market.filter(p=>s.day-p.created<5||p.featured&&s.day<4);const eligible=CATALOG.map((c,i)=>({c,i})).filter(x=>x.c[3]<=s.unlocked);for(let i=0;i<2;i++){const p=device(s,eligible[Math.floor(rng()*eligible.length)].i,rng);s.market.unshift(p);log(s,`Novo no marketplace: ${p.model} por ${money(p.price)}.`,'opportunity');}s.market=s.market.slice(0,12);checkpoint(s);}
