import test from 'node:test';
import assert from 'node:assert/strict';
import {initial,buy,inspect,list,negotiate,nextDay,worth,profit,value,checkpoint,active} from '../engine.js';
const stable=()=>.5;
function listed(){const s=initial(stable),id=s.market[0].id;buy(s,id);list(s,id,3500);return {s,id};}
function offer(s,id,overrides={}){const o={id:++s.seq,itemId:id,buyer:'Carlos',amount:3100,budget:3450,rounds:0,created:s.day,expires:s.day+2,...overrides};s.offers.push(o);s.inventory.find(p=>p.id===id).status='negociando';return o.id;}
test('exact starting opportunity and purchase accounting',()=>{const s=initial(stable),p=s.market[0];assert.equal(s.cash,5000);assert.equal(s.day,1);assert.equal(s.reputation,50);assert.equal(p.price,2500);assert.equal(p.battery,87);assert.equal(p.appearance,8);assert.equal(p.box,true);buy(s,p.id);assert.equal(s.cash,2500);assert.equal(worth(s),6000);assert.equal(profit(s),0);assert.throws(()=>buy(s,p.id));});
test('inspection charged exactly once, reveals defects, reduces valuation',()=>{const s=initial(stable),p=s.market[0];p.issues=[['Tela paralela',.19]];inspect(s,p.id);assert.equal(s.cash,4920);assert.equal(profit(s),-80);assert.ok(value(s,p)<3500);assert.throws(()=>inspect(s,p.id));buy(s,p.id);list(s,p.id,3000);const o=offer(s,p.id,{amount:3000});negotiate(s,o,'accept');assert.equal(s.cash,5420);assert.equal(profit(s),420);assert.equal(worth(s),5420);});
test('listing does not sell; acceptance credits once and removes competing offers',()=>{const {s,id}=listed();assert.equal(s.cash,2500);assert.equal(s.inventory[0].status,'anunciado');const o=offer(s,id);offer(s,id,{buyer:'Marcos'});negotiate(s,o,'accept');assert.equal(s.cash,5600);assert.equal(profit(s),600);assert.equal(s.reputation,53);assert.equal(active(s).length,0);assert.equal(s.offers.length,0);assert.throws(()=>negotiate(s,o,'accept'));assert.equal(s.cash,5600);});
test('all counteroffer outcomes and refusal leaves phone listed',()=>{let {s,id}=listed();let o=offer(s,id);assert.equal(negotiate(s,o,'counter',3450),'accepted');assert.equal(profit(s),950);({s,id}=listed());o=offer(s,id);assert.equal(negotiate(s,o,'counter',3600,()=>0),'counter');assert.ok(s.offers[0].amount>3100);assert.equal(s.cash,2500);assert.equal(negotiate(s,o,'counter',10000),'rejected');assert.equal(s.offers.length,0);assert.equal(s.inventory[0].status,'anunciado');});
test('invalid prices and insufficient balance never debit money',()=>{const {s,id}=listed();for(const price of [0,-100,NaN,Infinity,1000001])assert.throws(()=>list(s,id,price));s.cash=0;assert.throws(()=>buy(s,s.market[0].id));assert.throws(()=>inspect(s,s.market[0].id));assert.equal(s.cash,0);});
test('days produce offers, views, opportunities without automatic sale',()=>{const {s,id}=listed();nextDay(s,()=>.1);assert.equal(s.day,2);assert.ok(s.offers.length);assert.equal(s.cash,2500);assert.ok(s.inventory[0].views>0);assert.ok(s.feed.some(e=>e.type==='market'));assert.equal(s.inventory[0].status,'negociando');const old=s.offers[0].id;for(let i=0;i<3;i++)nextDay(s,()=>.99);assert.ok(!s.offers.some(o=>o.id===old));assert.equal(s.inventory[0].status,'anunciado');assert.equal(s.cash,2500);assert.ok(s.market.length<=12);});
test('hidden issues become visible after purchase, and achievements persist',()=>{const s=initial(stable),p=s.market[0];p.issues=[['Aparelho bloqueado',.78]];buy(s,p.id);assert.equal(s.inventory[0].revealed,false);nextDay(s,stable);assert.equal(s.inventory[0].revealed,true);s.cash=25000;checkpoint(s);assert.equal(s.unlocked,25000);assert.deepEqual(s.goals,[10000,25000]);s.cash=100;checkpoint(s);assert.equal(s.unlocked,25000);assert.equal(s.goals.length,2);});
test('JSON save roundtrip retains negotiations and financial state',()=>{const {s,id}=listed();offer(s,id);nextDay(s,stable);const restored=JSON.parse(JSON.stringify(s));assert.deepEqual(restored,s);negotiate(restored,restored.offers[0].id,'accept');assert.equal(profit(restored),600);});
test('seeded 300-day game preserves the cash ledger through trades and inspections',()=>{let seed=123;const rng=()=>{seed=(seed*1664525+1013904223)>>>0;return seed/4294967296;};const s=initial(rng);for(let day=0;day<300;day++){for(const o of [...s.offers])negotiate(s,o.id,'accept');const candidate=s.market.find(p=>p.price<s.cash&&p.price<value(s,p)*.8);if(candidate){if(s.cash>=candidate.price+80)inspect(s,candidate.id);buy(s,candidate.id);list(s,candidate.id,value(s,candidate));}nextDay(s,rng);const costs=s.inventory.reduce((a,p)=>a+p.cost,0);const sales=s.inventory.reduce((a,p)=>a+(p.soldPrice||0),0);assert.equal(s.cash,5000-costs+sales-s.expenses);assert.ok(s.cash>=0);assert.ok(s.reputation<=100);assert.equal(new Set(s.offers.map(o=>o.itemId)).size,s.offers.length);assert.ok(s.offers.every(o=>active(s).some(p=>p.id===o.itemId)));}assert.ok(s.inventory.some(p=>p.status==='vendido'));});
