export const cityCenter = {
  city: "Pinheiros",
  state: "ES",
  lat: -18.4149,
  lng: -40.2171
};

export const categories = [
  { id: "alimentacao", name: "Alimentação", icon: "🍴", description: "Restaurantes, lanches, padarias e cafés.", order: 1, active: true },
  { id: "bares", name: "Bares e Drinks", icon: "🍺", description: "Bares, música e petiscos.", order: 2, active: true },
  { id: "hospedagem", name: "Hospedagem", icon: "🛏", description: "Hotéis, pousadas e estadias.", order: 3, active: true },
  { id: "compras", name: "Compras", icon: "🛒", description: "Mercados, lojas e utilidades.", order: 4, active: true },
  { id: "servicos", name: "Serviços", icon: "🔧", description: "Serviços profissionais e manutenção.", order: 5, active: true },
  { id: "saude", name: "Saúde e Beleza", icon: "❤️", description: "Clínicas, salões, estética e bem-estar.", order: 6, active: true },
  { id: "postos", name: "Postos", icon: "⛽", description: "Combustível, troca de óleo e conveniência.", order: 7, active: true },
  { id: "farmacias", name: "Farmácias", icon: "💊", description: "Medicamentos, perfumaria e cuidados.", order: 8, active: true },
  { id: "bancos", name: "Bancos", icon: "🏦", description: "Bancos, caixas e serviços financeiros.", order: 9, active: true },
  { id: "automotivo", name: "Automotivo", icon: "🚗", description: "Oficinas, borracharias e autopeças.", order: 10, active: true },
  { id: "eventos", name: "Eventos", icon: "🎉", description: "Agenda cultural e comunitária.", order: 11, active: true },
  { id: "turismo", name: "Pontos da cidade", icon: "📍", description: "Praças, pontos conhecidos e turismo.", order: 12, active: true },
  { id: "transporte", name: "Transporte", icon: "🚕", description: "Táxi, mototáxi e aplicativos de mobilidade.", order: 13, active: true }
];

const img = (id, params = "auto=format&fit=crop&w=900&q=70") => `https://images.unsplash.com/${id}?${params}`;

export const sources = {
  prefeitura: "https://www.pinheiros.es.gov.br/",
  festaCarneSol2026: "https://www.pinheiros.es.gov.br/noticia/ler/16565/pinheiros-divulga-atracoes-da-festa-da-carne-de-sol-2026",
  impactoEventos2026: "https://www.pinheiros.es.gov.br/noticia/ler/16620/eventos-devem-injetar-mais-de-r-14-milhoes-na-economia-de-pinheiros-e-impulsionar-turismo-local",
  turismoES: "https://descubraoespiritosanto.es.gov.br/cidades/pinheiros",
  econodataRestaurantes: "https://www.econodata.com.br/empresas/es-pinheiros/restaurantes",
  agazetaDelivery: "https://www.agazeta.com.br/entretenimento/gastronomia/peca-em-casa-restaurantes-cafes-e-lanchonetes-com-delivery-0320",
  plusDeliveryVaga: "https://www.glassdoor.com.br/job-listing/executivo-de-contas-plus-delivery-magazine-luiza-JV_IC4147927_KO0%2C33_KE34%2C48.htm",
  taxiPinheiros: "https://telefonedetaxi.com/telefone-de-taxi-em_pinheiros-es/",
  indriveGooglePlay: "https://play.google.com/store/apps/details?hl=pt-BR&id=sinet.startup.inDriver&listing=br-moto"
};

export const establishments = [
  {
    id: "demo-001",
    name: "Café Praça Central - Exemplo",
    slug: "cafe-praca-central-exemplo",
    description: "Cafeteria demonstrativa para mostrar como um comércio real apareceria no TáOnde.",
    fullDescription: "Ambiente aconchegante, cafés especiais, salgados, doces e opções rápidas para encontros no centro. Este cadastro é demonstrativo e não representa uma empresa real.",
    category: "alimentacao",
    subcategory: "Cafeteria",
    address: "Rua das Flores, 123",
    neighborhood: "Centro",
    city: "Pinheiros",
    state: "ES",
    zip: "29980-000",
    lat: -18.4141,
    lng: -40.2181,
    phone: "(27) 3000-1001",
    whatsapp: "552730001001",
    instagram: "@taonde.exemplo",
    site: "https://example.com",
    hours: { mon: [["07:00", "20:00"]], tue: [["07:00", "20:00"]], wed: [["07:00", "20:00"]], thu: [["07:00", "20:00"]], fri: [["07:00", "21:00"]], sat: [["08:00", "18:00"]], sun: [] },
    photos: [img("photo-1509042239860-f550ce710b93"), img("photo-1495474472287-4d71bcdd2085"), img("photo-1511920170033-f8396924c348")],
    cover: img("photo-1509042239860-f550ce710b93"),
    payments: ["Pix", "Cartão", "Dinheiro"],
    services: ["Café especial", "Lanches", "Sobremesas", "Retirada"],
    rating: 4.8,
    reviewCount: 126,
    featured: true,
    delivery: true,
    active: true
  },
  {
    id: "demo-002",
    name: "Pizzaria Sabor da Cidade - Exemplo",
    slug: "pizzaria-sabor-da-cidade-exemplo",
    description: "Pizzas, massas e delivery em cadastro demonstrativo.",
    fullDescription: "Página exemplo para pizzarias e restaurantes com cardápio, delivery, contato rápido e rota.",
    category: "alimentacao",
    subcategory: "Pizzaria",
    address: "Av. Brasil, 560",
    neighborhood: "Centro",
    city: "Pinheiros",
    state: "ES",
    zip: "29980-000",
    lat: -18.416,
    lng: -40.221,
    phone: "(27) 3000-2002",
    whatsapp: "552730002002",
    instagram: "@pizzaria.exemplo",
    hours: { mon: [], tue: [["18:00", "23:30"]], wed: [["18:00", "23:30"]], thu: [["18:00", "23:30"]], fri: [["18:00", "00:30"]], sat: [["18:00", "00:30"]], sun: [["18:00", "23:00"]] },
    photos: [img("photo-1513104890138-7c749659a591"), img("photo-1565299624946-b28f40a0ae38"), img("photo-1574071318508-1cdbab80d002")],
    cover: img("photo-1513104890138-7c749659a591"),
    payments: ["Pix", "Cartão"],
    services: ["Delivery", "Retirada", "Rodízio"],
    rating: 4.7,
    reviewCount: 93,
    featured: true,
    delivery: true,
    active: true
  },
  {
    id: "demo-003",
    name: "Farmácia Saúde Já - Exemplo",
    slug: "farmacia-saude-ja-exemplo",
    description: "Medicamentos e perfumaria com WhatsApp para atendimento.",
    fullDescription: "Exemplo de cadastro para farmácias com funcionamento, telefone e localização.",
    category: "farmacias",
    subcategory: "Farmácia",
    address: "Rua Principal, 84",
    neighborhood: "Centro",
    city: "Pinheiros",
    state: "ES",
    zip: "29980-000",
    lat: -18.4128,
    lng: -40.2162,
    phone: "(27) 3000-3003",
    whatsapp: "552730003003",
    hours: { mon: [["08:00", "21:00"]], tue: [["08:00", "21:00"]], wed: [["08:00", "21:00"]], thu: [["08:00", "21:00"]], fri: [["08:00", "21:00"]], sat: [["08:00", "20:00"]], sun: [["08:00", "12:00"]] },
    photos: [img("photo-1576602976047-174e57a47881"), img("photo-1587854692152-cbe660dbde88")],
    cover: img("photo-1576602976047-174e57a47881"),
    payments: ["Pix", "Cartão", "Dinheiro"],
    services: ["Medicamentos", "Perfumaria", "Delivery"],
    rating: 4.6,
    reviewCount: 58,
    featured: false,
    delivery: true,
    active: true
  },
  {
    id: "demo-004",
    name: "Auto Center Pinheiros - Exemplo",
    slug: "auto-center-pinheiros-exemplo",
    description: "Oficina, pneus, borracharia e revisão automotiva.",
    fullDescription: "Cadastro demonstrativo para oficinas, borracharias e serviços automotivos.",
    category: "automotivo",
    subcategory: "Oficina e borracharia",
    address: "Rodovia Norte, km 2",
    neighborhood: "Saída Norte",
    city: "Pinheiros",
    state: "ES",
    zip: "29980-000",
    lat: -18.4089,
    lng: -40.224,
    phone: "(27) 3000-4004",
    whatsapp: "552730004004",
    hours: { mon: [["07:30", "18:00"]], tue: [["07:30", "18:00"]], wed: [["07:30", "18:00"]], thu: [["07:30", "18:00"]], fri: [["07:30", "18:00"]], sat: [["08:00", "12:00"]], sun: [] },
    photos: [img("photo-1486262715619-67b85e0b08d3"), img("photo-1632823471565-1ecdf5c41575")],
    cover: img("photo-1486262715619-67b85e0b08d3"),
    payments: ["Pix", "Cartão"],
    services: ["Borracharia", "Pneus", "Alinhamento", "Revisão"],
    rating: 4.5,
    reviewCount: 41,
    featured: false,
    delivery: false,
    active: true
  },
  {
    id: "demo-005",
    name: "Mercado Família - Exemplo",
    slug: "mercado-familia-exemplo",
    description: "Supermercado demonstrativo com itens de rotina.",
    fullDescription: "Exemplo de cadastro para supermercados e mercearias da cidade.",
    category: "compras",
    subcategory: "Supermercado",
    address: "Rua das Palmeiras, 210",
    neighborhood: "Canário",
    city: "Pinheiros",
    state: "ES",
    lat: -18.4198,
    lng: -40.2158,
    phone: "(27) 3000-5005",
    whatsapp: "552730005005",
    hours: { mon: [["07:00", "19:30"]], tue: [["07:00", "19:30"]], wed: [["07:00", "19:30"]], thu: [["07:00", "19:30"]], fri: [["07:00", "20:00"]], sat: [["07:00", "18:00"]], sun: [["08:00", "12:00"]] },
    photos: [img("photo-1542838132-92c53300491e"), img("photo-1578916171728-46686eac8d58")],
    cover: img("photo-1542838132-92c53300491e"),
    payments: ["Pix", "Cartão", "Dinheiro", "Vale alimentação"],
    services: ["Açougue", "Hortifruti", "Entrega"],
    rating: 4.4,
    reviewCount: 77,
    featured: true,
    delivery: true,
    active: true
  },
  {
    id: "demo-006",
    name: "Hotel Rota Verde - Exemplo",
    slug: "hotel-rota-verde-exemplo",
    description: "Hospedagem demonstrativa para visitantes e representantes.",
    fullDescription: "Página exemplo para hotéis e pousadas, com fotos, contatos e rota.",
    category: "hospedagem",
    subcategory: "Hotel",
    address: "Av. dos Ipês, 30",
    neighborhood: "Centro",
    city: "Pinheiros",
    state: "ES",
    lat: -18.4119,
    lng: -40.2198,
    phone: "(27) 3000-6006",
    whatsapp: "552730006006",
    site: "https://example.com/hotel",
    hours: { mon: [["00:00", "23:59"]], tue: [["00:00", "23:59"]], wed: [["00:00", "23:59"]], thu: [["00:00", "23:59"]], fri: [["00:00", "23:59"]], sat: [["00:00", "23:59"]], sun: [["00:00", "23:59"]] },
    photos: [img("photo-1566073771259-6a8506099945"), img("photo-1564501049412-61c2a3083791")],
    cover: img("photo-1566073771259-6a8506099945"),
    payments: ["Pix", "Cartão"],
    services: ["Wi-Fi", "Café da manhã", "Estacionamento"],
    rating: 4.3,
    reviewCount: 35,
    featured: false,
    delivery: false,
    active: true
  },
  {
    id: "demo-007",
    name: "Praça Municipal - Ponto Exemplo",
    slug: "praca-municipal-ponto-exemplo",
    description: "Ponto de referência demonstrativo para turismo e localização.",
    fullDescription: "Exemplo de ponto da cidade para orientar visitantes e moradores.",
    category: "turismo",
    subcategory: "Ponto da cidade",
    address: "Centro",
    neighborhood: "Centro",
    city: "Pinheiros",
    state: "ES",
    lat: -18.4147,
    lng: -40.217,
    hours: { mon: [["00:00", "23:59"]], tue: [["00:00", "23:59"]], wed: [["00:00", "23:59"]], thu: [["00:00", "23:59"]], fri: [["00:00", "23:59"]], sat: [["00:00", "23:59"]], sun: [["00:00", "23:59"]] },
    photos: [img("photo-1518005020951-eccb494ad742"), img("photo-1494526585095-c41746248156")],
    cover: img("photo-1518005020951-eccb494ad742"),
    payments: [],
    services: ["Referência urbana", "Lazer"],
    rating: 4.6,
    reviewCount: 22,
    featured: true,
    delivery: false,
    active: true
  },
  {
    id: "real-food-001",
    name: "Restaurante da Lia",
    slug: "restaurante-da-lia",
    description: "Registro real identificado em amostra pública de empresas de restaurantes em Pinheiros/ES. Informações comerciais devem ser validadas pelo responsável.",
    fullDescription: "Empresa real listada em fonte pública como Restaurante & Lavanderia da Lia Ltda, CNPJ 55.039.504/0001-07, no setor de restaurantes em Pinheiros/ES. Horários, telefone, cardápio e fotos oficiais ainda precisam de validação cadastral.",
    category: "alimentacao",
    subcategory: "Restaurante",
    address: "Córrego Jundiá",
    neighborhood: "Zona rural",
    city: "Pinheiros",
    state: "ES",
    zip: "29980-000",
    lat: -18.4149,
    lng: -40.2171,
    geocodeStatus: "aproximado",
    cnpj: "55.039.504/0001-07",
    hours: null,
    photos: [img("photo-1555396273-367ea4eb4db5")],
    cover: img("photo-1555396273-367ea4eb4db5"),
    payments: [],
    services: ["Restaurante"],
    rating: null,
    reviewCount: 0,
    featured: true,
    delivery: false,
    active: true,
    verified: true,
    sourceName: "Econodata",
    sourceUrl: sources.econodataRestaurantes
  },
  {
    id: "real-food-002",
    name: "Fogão a Lenha",
    slug: "fogao-a-lenha",
    description: "Restaurante real identificado em amostra pública de CNPJ/empresas de Pinheiros/ES.",
    fullDescription: "Registro listado publicamente como Sidyones Moreira Carlini, CNPJ 31.740.122/0001-48, nome fantasia Fogão a Lenha. Dados de contato, funcionamento e fotos oficiais precisam ser confirmados.",
    category: "alimentacao",
    subcategory: "Restaurante",
    address: "Rua Gil Veloso, 572",
    neighborhood: "Pinheiros",
    city: "Pinheiros",
    state: "ES",
    zip: "29980-000",
    lat: -18.4149,
    lng: -40.2171,
    geocodeStatus: "aproximado",
    cnpj: "31.740.122/0001-48",
    hours: null,
    photos: [img("photo-1540189549336-e6e99c3679fe")],
    cover: img("photo-1540189549336-e6e99c3679fe"),
    payments: [],
    services: ["Restaurante"],
    rating: null,
    reviewCount: 0,
    featured: true,
    delivery: false,
    active: true,
    verified: true,
    sourceName: "Econodata",
    sourceUrl: sources.econodataRestaurantes
  },
  {
    id: "real-food-003",
    name: "Fruta Creme",
    slug: "fruta-creme",
    description: "Sorveteria/restaurante real identificado em fonte pública de empresas de Pinheiros/ES.",
    fullDescription: "Registro listado publicamente como Fruta Creme Sorvetes Matriz Pinheiros Ltda, CNPJ 38.134.575/0001-70. Cadastro aguardando validação de contato, horário e imagens próprias.",
    category: "alimentacao",
    subcategory: "Sorveteria",
    address: "Avenida Agenor Luiz Heringer, 754 A",
    neighborhood: "Centro",
    city: "Pinheiros",
    state: "ES",
    zip: "29980-000",
    lat: -18.4149,
    lng: -40.2171,
    geocodeStatus: "aproximado",
    cnpj: "38.134.575/0001-70",
    hours: null,
    photos: [img("photo-1501443762994-82bd5dace89a")],
    cover: img("photo-1501443762994-82bd5dace89a"),
    payments: [],
    services: ["Sorvetes", "Lanches"],
    rating: null,
    reviewCount: 0,
    featured: true,
    delivery: false,
    active: true,
    verified: true,
    sourceName: "Econodata",
    sourceUrl: sources.econodataRestaurantes
  },
  {
    id: "real-food-004",
    name: "Churrascaria do Baixinho",
    slug: "churrascaria-do-baixinho",
    description: "Estabelecimento real citado em amostra pública de empresas de restaurantes em Pinheiros/ES.",
    fullDescription: "Registro listado publicamente como Nordeste Capixaba Serviços Alimentícios Ltda, CNPJ 32.713.502/0001-56, nome Churrascaria do Baixinho. Necessário validar dados operacionais.",
    category: "alimentacao",
    subcategory: "Churrascaria",
    address: "Avenida Agenor Luiz Heringer, 739",
    neighborhood: "Centro",
    city: "Pinheiros",
    state: "ES",
    zip: "29980-000",
    lat: -18.4149,
    lng: -40.2171,
    geocodeStatus: "aproximado",
    cnpj: "32.713.502/0001-56",
    hours: null,
    photos: [img("photo-1558030006-450675393462")],
    cover: img("photo-1558030006-450675393462"),
    payments: [],
    services: ["Churrascaria", "Refeições"],
    rating: null,
    reviewCount: 0,
    featured: false,
    delivery: false,
    active: true,
    verified: true,
    sourceName: "Econodata",
    sourceUrl: sources.econodataRestaurantes
  },
  {
    id: "real-food-005",
    name: "Parada Barbecue",
    slug: "parada-barbecue",
    description: "Restaurante de Pinheiros citado em guia público de delivery do ES.",
    fullDescription: "Estabelecimento citado por A Gazeta em guia de delivery no Espírito Santo como localizado no Centro de Pinheiros, com atendimento por delivery informado na publicação.",
    category: "alimentacao",
    subcategory: "Barbecue",
    address: "Centro",
    neighborhood: "Centro",
    city: "Pinheiros",
    state: "ES",
    lat: -18.4149,
    lng: -40.2171,
    geocodeStatus: "aproximado",
    phone: "(27) 99908-7202",
    whatsapp: "5527999087202",
    hours: null,
    photos: [img("photo-1529193591184-b1d58069ecdd")],
    cover: img("photo-1529193591184-b1d58069ecdd"),
    payments: [],
    services: ["Delivery", "Restaurante"],
    rating: null,
    reviewCount: 0,
    featured: true,
    delivery: true,
    active: true,
    verified: true,
    sourceName: "A Gazeta",
    sourceUrl: sources.agazetaDelivery
  },
  {
    id: "real-food-006",
    name: "Cakes do Léo",
    slug: "cakes-do-leo",
    description: "Estabelecimento de Pinheiros citado em guia público de delivery do ES.",
    fullDescription: "Estabelecimento citado por A Gazeta em guia de delivery no Espírito Santo como localizado no Centro de Pinheiros, com telefone de delivery publicado.",
    category: "alimentacao",
    subcategory: "Doces e bolos",
    address: "Centro",
    neighborhood: "Centro",
    city: "Pinheiros",
    state: "ES",
    lat: -18.4149,
    lng: -40.2171,
    geocodeStatus: "aproximado",
    phone: "(27) 99605-8195",
    whatsapp: "5527996058195",
    hours: null,
    photos: [img("photo-1578985545062-69928b1d9587")],
    cover: img("photo-1578985545062-69928b1d9587"),
    payments: [],
    services: ["Bolos", "Encomendas", "Delivery"],
    rating: null,
    reviewCount: 0,
    featured: false,
    delivery: true,
    active: true,
    verified: true,
    sourceName: "A Gazeta",
    sourceUrl: sources.agazetaDelivery
  },
  {
    id: "real-tour-001",
    name: "Igreja Matriz São João Evangelista",
    slug: "igreja-matriz-sao-joao-evangelista",
    description: "Atração turística de Pinheiros listada no portal Descubra o Espírito Santo.",
    fullDescription: "Ponto turístico real de Pinheiros/ES listado pelo portal oficial de turismo Descubra o Espírito Santo.",
    category: "turismo",
    subcategory: "Turismo",
    address: "Pinheiros",
    neighborhood: "Centro",
    city: "Pinheiros",
    state: "ES",
    lat: -18.4149,
    lng: -40.2171,
    geocodeStatus: "aproximado",
    hours: null,
    photos: [img("photo-1520637736862-4d197d17c35a")],
    cover: img("photo-1520637736862-4d197d17c35a"),
    payments: [],
    services: ["Ponto turístico", "Patrimônio local"],
    rating: null,
    reviewCount: 0,
    featured: true,
    delivery: false,
    active: true,
    verified: true,
    sourceName: "Descubra o Espírito Santo",
    sourceUrl: sources.turismoES
  },
  {
    id: "real-tour-002",
    name: "Reserva Biológica de Córrego do Veado",
    slug: "reserva-biologica-de-corrego-do-veado",
    description: "Atração natural de Pinheiros listada em portal oficial de turismo do Espírito Santo.",
    fullDescription: "Reserva biológica citada entre as atrações turísticas de Pinheiros no portal Descubra o Espírito Santo e também mencionada em notícia da Prefeitura sobre potencialidades turísticas.",
    category: "turismo",
    subcategory: "Natureza",
    address: "Pinheiros",
    neighborhood: "Zona rural",
    city: "Pinheiros",
    state: "ES",
    lat: -18.4149,
    lng: -40.2171,
    geocodeStatus: "aproximado",
    hours: null,
    photos: [img("photo-1448375240586-882707db888b")],
    cover: img("photo-1448375240586-882707db888b"),
    payments: [],
    services: ["Natureza", "Turismo"],
    rating: null,
    reviewCount: 0,
    featured: true,
    delivery: false,
    active: true,
    verified: true,
    sourceName: "Descubra o Espírito Santo",
    sourceUrl: sources.turismoES
  },
  {
    id: "real-tour-003",
    name: "Parque da Vaquejada",
    slug: "parque-da-vaquejada",
    description: "Ponto turístico/eventivo de Pinheiros listado no portal Descubra o Espírito Santo.",
    fullDescription: "Atração listada pelo portal Descubra o Espírito Santo. A Prefeitura também divulga a vaquejada como parte de eventos culturais de Pinheiros.",
    category: "turismo",
    subcategory: "Eventos e turismo",
    address: "Pinheiros",
    neighborhood: "Pinheiros",
    city: "Pinheiros",
    state: "ES",
    lat: -18.4149,
    lng: -40.2171,
    geocodeStatus: "aproximado",
    hours: null,
    photos: [img("photo-1517457373958-b7bdd4587205")],
    cover: img("photo-1517457373958-b7bdd4587205"),
    payments: [],
    services: ["Eventos", "Turismo"],
    rating: null,
    reviewCount: 0,
    featured: true,
    delivery: false,
    active: true,
    verified: true,
    sourceName: "Descubra o Espírito Santo",
    sourceUrl: sources.turismoES
  },
  {
    id: "real-transport-001",
    name: "Apps de transporte em Pinheiros",
    slug: "apps-de-transporte-em-pinheiros",
    description: "Registro informativo para orientar usuários sobre apps e alternativas de mobilidade. Disponibilidade deve ser conferida no aplicativo escolhido.",
    fullDescription: "Fontes públicas indicam táxi/mototáxi em Pinheiros e citam apps nacionais como Uber, 99, Cabify/Easy Taxi em contexto de transporte por aplicativo. Não há catálogo público local de motoristas para importar; por isso o TáOnde abre como informação orientativa, sem afirmar disponibilidade em tempo real.",
    category: "transporte",
    subcategory: "Mobilidade",
    address: "Pinheiros",
    neighborhood: "Pinheiros",
    city: "Pinheiros",
    state: "ES",
    lat: -18.4149,
    lng: -40.2171,
    geocodeStatus: "cidade",
    hours: null,
    photos: [img("photo-1449965408869-eaa3f722e40d")],
    cover: img("photo-1449965408869-eaa3f722e40d"),
    payments: [],
    services: ["Táxi", "Mototáxi", "Uber", "99", "inDrive"],
    rating: null,
    reviewCount: 0,
    featured: false,
    delivery: false,
    active: true,
    verified: false,
    sourceName: "Fontes públicas de transporte",
    sourceUrl: sources.taxiPinheiros
  }
];

export const events = [
  {
    id: "real-event-001",
    name: "Festa da Carne de Sol 2026",
    slug: "festa-da-carne-de-sol-2026",
    description: "Programação oficial divulgada pela Prefeitura de Pinheiros para os dias 17, 18 e 19 de abril de 2026, com shows, Corrida do Contorno, Caminhada do Contorno, Vaquejada, parque de diversões e praça de alimentação.",
    image: img("photo-1501281668745-f7f57925c3b4"),
    date: "2026-04-17",
    time: "19:00",
    place: "Praça Augusto Ruschi",
    address: "Bairro Santo Antônio, Pinheiros - ES",
    lat: -18.4149,
    lng: -40.2171,
    price: "Consultar programação",
    free: false,
    link: sources.festaCarneSol2026,
    featured: false,
    active: true,
    real: true,
    sourceName: "Prefeitura de Pinheiros",
    sourceUrl: sources.festaCarneSol2026
  },
  {
    id: "real-event-002",
    name: "Arraiá da Pedra Furada",
    slug: "arraia-da-pedra-furada",
    description: "Festa tradicional de Pinheiros listada pelo portal Descubra o Espírito Santo e citada pela Prefeitura em notícia sobre o potencial turístico do município.",
    image: img("photo-1533174072545-7a4b6ad7a6c3"),
    date: "2025-06-18",
    time: "18:00",
    place: "São João do Sobrado",
    address: "São João do Sobrado, Pinheiros - ES",
    lat: -18.4149,
    lng: -40.2171,
    price: "Consultar programação anual",
    free: false,
    link: sources.turismoES,
    featured: false,
    active: true,
    real: true,
    sourceName: "Descubra o Espírito Santo",
    sourceUrl: sources.turismoES
  },
  {
    id: "evt-001",
    name: "Festival de Música na Praça - Exemplo",
    slug: "festival-de-musica-na-praca-exemplo",
    description: "Evento demonstrativo com apresentações musicais e praça de alimentação.",
    image: img("photo-1501386761578-eac5c94b800a"),
    date: "2026-08-15",
    time: "19:00",
    place: "Praça Municipal",
    address: "Centro, Pinheiros - ES",
    lat: -18.4147,
    lng: -40.217,
    price: "Gratuito",
    free: true,
    link: "https://example.com/evento",
    featured: true,
    active: true
  },
  {
    id: "evt-002",
    name: "Feira de Artesanato - Exemplo",
    slug: "feira-de-artesanato-exemplo",
    description: "Feira demonstrativa com artesãos locais, comidas e lembranças.",
    image: img("photo-1519671482749-fd09be7ccebf"),
    date: "2026-08-16",
    time: "08:00",
    place: "Centro",
    address: "Rua Principal, Pinheiros - ES",
    lat: -18.414,
    lng: -40.216,
    price: "Gratuito",
    free: true,
    featured: false,
    active: true
  },
  {
    id: "evt-003",
    name: "Noite de Jazz - Exemplo",
    slug: "noite-de-jazz-exemplo",
    description: "Evento demonstrativo em bar local com música ao vivo.",
    image: img("photo-1511192336575-5a79af67a629"),
    date: "2026-08-22",
    time: "20:00",
    place: "Espaço Cultural",
    address: "Av. Brasil, Pinheiros - ES",
    lat: -18.416,
    lng: -40.221,
    price: "R$ 25",
    free: false,
    featured: false,
    active: true
  }
];

export const banners = [
  {
    title: "Descubra Pinheiros com praticidade",
    subtitle: "Comércios, serviços, eventos e pontos da cidade em um só lugar.",
    image: img("photo-1518005020951-eccb494ad742"),
    tag: "Destaque"
  },
  {
    title: "Gastronomia perto de você",
    subtitle: "Encontre restaurantes, cafés, pizzarias e delivery.",
    image: img("photo-1555396273-367ea4eb4db5"),
    tag: "Alimentação"
  },
  {
    title: "Eventos imperdíveis",
    subtitle: "Acompanhe a agenda local e salve seus favoritos.",
    image: img("photo-1501281668745-f7f57925c3b4"),
    tag: "Agenda"
  }
];
